[ci] add "retry" func and use it with "docker run"

diff --git a/.ci/Makefile.ci b/.ci/Makefile.ci
--- a/.ci/Makefile.ci
+++ b/.ci/Makefile.ci
@@ -4,13 +4,23 @@ GOVERSION ?= 1.17
 
 ELASTICSEARCH_NAME ?= terraform-elasticstack-es
 ELASTICSEARCH_ENDPOINTS ?= http://$(ELASTICSEARCH_NAME):9200
-ELASTICSEARCH_VERSION ?= 7.15.0
+ELASTICSEARCH_VERSION ?= 7.15.1
 ELASTICSEARCH_USERNAME ?= elastic
 ELASTICSEARCH_PASSWORD ?= changeme
 ELASTICSEARCH_NETWORK ?= elasticstack-network
 ELASTICSEARCH_MEM ?= 1024m
 
 SOURCE_LOCATION ?= $(shell pwd)
+
+# Retry command - first argumment is how many attempts are required, second argument is the command to run
+# Backoff starts with 1 second and double with next itteration
+retry = until [ $$(if [ -z "$$attempt" ]; then echo -n "0"; else echo -n "$$attempt"; fi) -ge $(1) ]; do \
+		backoff=$$(if [ -z "$$backoff" ]; then echo "1"; else echo "$$backoff"; fi); \
+		sleep $$backoff; \
+		$(2) && break; \
+		attempt=$$((attempt + 1)); \
+		backoff=$$((backoff * 2)); \
+	done
 
 .PHONY: docker-testacc
 docker-testacc: docker-elasticsearch ## Run acceptance tests in the docker container
@@ -26,7 +36,7 @@ docker-testacc: docker-elasticsearch ## Run acceptance tests in the docker conta
 
 .PHONY: docker-elasticsearch
 docker-elasticsearch: docker-network ## Start Elasticsearch single node cluster in docker container
-	@ if ! docker ps --format '{{.Names}}' | grep -w $(ELASTICSEARCH_NAME) > /dev/null 2>&1 ; then \
+	@ $(call retry, 5, if ! docker ps --format '{{.Names}}' | grep -w $(ELASTICSEARCH_NAME) > /dev/null 2>&1 ; then \
 		docker run -d \
 		--memory $(ELASTICSEARCH_MEM) \
 		-p 9200:9200 -p 9300:9300 \
@@ -36,7 +46,7 @@ docker-elasticsearch: docker-network ## Start Elasticsearch single node cluster 
 		--name $(ELASTICSEARCH_NAME) \
 		--network $(ELASTICSEARCH_NETWORK) \
 		docker.elastic.co/elasticsearch/elasticsearch:$(ELASTICSEARCH_VERSION); \
-		fi
+		fi)
 
 
 .PHONY: docker-network
